name: New Project Configuration
description: New NREL - hosted OpenPATH deployment configuration
title: New Project Configuration - [PROJECT]
labels: ['new config']
body:
- type: markdown
  attributes:
    value: "To get started with a customized deployment, please fill out this form. Once you complete the form, a configuration file will be generated and if it is error free, it will be merged into our repository."
- type: input
  id: deployment_name
  attributes:
    label: Project Name
    description: Also update `[PROJECT]` in the title above
  validations:
    required: true
- type: input
  id: deployment_partner_name
  attributes:
    label: Deployment Partner Name
    description: The name of your group or institution.
  validations:
    required: true
- type: input
  id: url_abbreviation
  attributes:
    label: Shortened Name
    description: This will become part of the url for your deployment's join page - could be an abbreviation, or along the lines of open-access-study.
  validations:
    required: true
- type: dropdown
  id: program_or_study
  attributes:
    label: Program or Study?
    description: Choose if your project will be a program or a study -- choose program if you'd like to designate a mode of interest.
    options:
      - program
      - study
  validations:
    required: true
- type: dropdown
  id: autogen
  attributes:
    label: Autogenerate OPcodes?
    description: Choose if opcodes will be autogenerated - if true, the opcodes will be randomly generated on each load of the join page where participants can copy or scan the code, if false you will need to distribute the opcodes.  
    options:
      - 'true'
      - 'false'
  validations:
    required: true
- type: input
  id: subgroups
  attributes: 
    label: OPcode Subgroups
    description: Please enter a list separated by commas.
    placeholder: test, default
  validations: 
    required: false
- type: input
  id: start
  attributes:
    label: Start Month
    description: Month and year of project start
    placeholder: 01/2024
  validations:
    required: true
- type: input
  id: program_admin_contact
  attributes: 
    label: Program Admin Contact
    description: Name and contact info, to be inserted into templated parts of app
    placeholder: "K. Shankari, NREL (email: k.shankari@nrel.gov, phone: 123-456-7890)"
  validations:
    required: true


