name: New Project Configuration
description: New NREL - hosted OpenPATH deployment configuration
title: New Project Configuration - [PROJECT]
labels: ['new config']
body:
- type: markdown
  attributes:
    value: "# Project Deployment Config"
- type: markdown
  attributes:
    value: "To get started with a customized deployment, please fill out this form. Once you complete the form, a configuration file will be generated and if it is error free, it will be merged into our repository."
- type: input
  id: url_abbreviation
  attributes:
    label: Shortened Name
    description: This will become part of the url for your deployment's join page - could be an abbreviation, or along the lines of open-access-study.
  validations:
    required: true
- type: dropdown
  id: program_or_study
  attributes:
    label: Program or Study?
    description: Choose if your project will be a program or a study -- choose program if you'd like to designate a mode of interest.
    options:
      - program
      - study
  validations:
    required: true
- type: dropdown
  id: autogen
  attributes:
    label: Autogenerate OPcodes?
    description: Choose if opcodes will be autogenerated - if true, the opcodes will be randomly generated on each load of the join page where participants can copy or scan the code, if false you will need to distribute the opcodes.  
    options:
      - 'true'
      - 'false'
  validations:
    required: true
- type: input
  id: subgroups
  attributes: 
    label: OPcode Subgroups
    description: Please enter a list separated by commas.
    placeholder: test, default
  validations: 
    required: false
- type: input
  id: start
  attributes:
    label: Start Month
    description: Month and year of project start
    placeholder: 01/2024
  validations:
    required: true
- type: input
  id: program_admin_contact
  attributes: 
    label: Program Admin Contact
    description: Name and contact info, to be inserted into templated parts of app
    placeholder: "K. Shankari, NREL (email: k.shankari@nrel.gov, phone: 123-456-7890)"
  validations:
    required: true
- type: markdown
  attributes:
    value: "# Translated Text"
- type: markdown
  attributes:
    value: "## First Language"
- type: markdown
  attributes:
    value: "Please enter text for the languages you would like to support. Most projects include English and Spanish, contact us if you have questions about languge support."
- type: dropdown
  id: lang_1
  attributes: 
    label: First Language
    description: Select primary language.
    options:
      - en
      - es
      - lo
  validations:
    required: true
- type: input
  id: deployment_partner_name_lang1
  attributes:
    label: Deployment Partner Name
    description: The name of your group or institution.
  validations:
    required: true
- type: input
  id: deployment_name_lang1
  attributes:
    label: Project Name
    description: Also update `[PROJECT]` in the title above
  validations:
    required: true
- type: input
  id: summary_line_1_lang1
  attributes:
    label: Summary Line 1
    description: 
  validations:
    required: true
- type: input
  id: summary_line_2_lang1
  attributes:
    label: Summary Line 2
    description: 
  validations:
    required: false
- type: input
  id: summary_line_3_lang1
  attributes:
    label: Summary Line 3
    description: 
  validations:
    required: false
- type: input
  id: short_textual_description_lang1
  attributes:
    label: Short Textual Description
    description: 
  validations:
    required: true
- type: input
  id: why_we_collect_lang1
  attributes:
    label: Why We Collect
    description: The purpose of your data collection efforts
  validations:
    required: true
- type: input
  id: research_question_1_lang1
  attributes:
    label: Research Question
    description: If applicable, what are the research questions for this project?
  validations:
    required: false
- type: input
  id: research_question_2_lang1
  attributes:
    label: Research Question
    description: If applicable, what are the research questions for this project?
  validations:
    required: false
- type: input
  id: research_question_3_lang1
  attributes:
    label: Research Question
    description: If applicable, what are the research questions for this project?
  validations:
    required: false

- type: markdown
  attributes:
    value: "## Second Language"
- type: dropdown
  id: lang_2
  attributes: 
    label: Second Language
    description: Select secondary language.
    options:
      - en
      - es
      - lo
  validations:
    required: false
- type: input
  id: deployment_partner_name_lang2
  attributes:
    label: Deployment Partner Name
    description: The name of your group or institution.
  validations:
    required: false
- type: input
  id: deployment_name_lang2
  attributes:
    label: Project Name
    description: Also update `[PROJECT]` in the title above
  validations:
    required: false
- type: input
  id: summary_line_1_lang2
  attributes:
    label: Summary Line 1
    description: 
  validations:
    required: false
- type: input
  id: summary_line_2_lang2
  attributes:
    label: Summary Line 2
    description: 
  validations:
    required: false
- type: input
  id: summary_line_3_lang2
  attributes:
    label: Summary Line 3
    description: 
  validations:
    required: false
- type: input
  id: short_textual_description_lang2
  attributes:
    label: Short Textual Description
    description: 
  validations:
    required: false
- type: input
  id: why_we_collect_lang2
  attributes:
    label: Why We Collect
    description: The purpose of your data collection efforts
  validations:
    required: false
- type: input
  id: research_question_1_lang2
  attributes:
    label: Research Question
    description: If applicable, what are the research questions for this project?
  validations:
    required: false
- type: input
  id: research_question_2_lang2
  attributes:
    label: Research Question
    description: If applicable, what are the research questions for this project?
  validations:
    required: false
- type: input
  id: research_question_3_lang2
  attributes:
    label: Research Question
    description: If applicable, what are the research questions for this project?
  validations:
    required: false

- type: markdown
  attributes:
    value: "## App Settings"
- type: dropdown
  id: use_imperial
  attributes:
    label: Use imperial units of measure
    options:
      - "true"
      - "false"
  validations:
    required: true
- type: dropdown
  id: include_test_users
  attributes:
    label: Include test users in metrics?
    options: 
      - "true"
      - "false"
  validations:
    required: true
- type: dropdown
  id: trip_end_notification
  attributes:
    label: Send notifications at trip end?
    options: 
      - "true"
      - "false"
  validations:
    required: true

- type: markdown
  attributes:
    value: "## Survey Configurations"

- type: markdown
  attributes:
    value: "## Reminder Schemes"

- type: markdown
  attributes:
    value: "## Administrative Dashboard"
- type: markdown
  id: research_question_3_lang2
  attributes:
    value: "These values control the administrative dashboard"
- type: dropdown
  id: overview_users
  attributes:
    label: Overview Users
    description: 
    default: 0
    options:  
      - "true"
      - "false"
  validations:
    required: true
- type: dropdown
  id: overview_active_users
  attributes:
    label: Overview Active Users
    description: 
    default: 0
    options:  
      - "true"
      - "false"
  validations:
    required: true
- type: dropdown
  id: overview_trips
  attributes:
    label: Overview Trips
    description: 
    default: 0
    options:  
      - "true"
      - "false"
  validations:
    required: true
- type: dropdown
  id: overview_signup_trends
  attributes:
    label: Overview Signup Trends
    description: 
    default: 0
    options:  
      - "true"
      - "false"
  validations:
    required: true
- type: dropdown
  id: overview_trips_trend
  attributes:
    label: Overview Trips Trend
    description: 
    default: 0
    options:  
      - "true"
      - "false"
  validations:
    required: true
- type: dropdown
  id: data_uuids
  attributes:
    label: Data UUIDs
    description: 
    default: 0
    options:  
      - "true"
      - "false"
  validations:
    required: true
- type: dropdown
  id: data_trips
  attributes:
    label: Data Trips
    description: 
    default: 0
    options:  
      - "true"
      - "false"
  validations:
    required: true
- type: input
  id: data_trips_columns_exclude
  attributes:
    label: Data Trips Columns Exclude 
    description: Please input columns to exclude, separated by commas
- type: input
  id: additional_trip_columns
  attributes:
    label: Additional Trip Columns
    description: Please input columns, separated by commas
- type: input
  id: data_uuids_columns_exclude
  attributes:
    label: Data Trips Columns Exclude 
    description: Please input columns to exclude, separated by commas
- type: dropdown
  id: token_generate
  attributes:
    label: Generate tokens
    description: 
    default: 0
    options:  
      - "true"
      - "false"
  validations:
    required: true
- type: input
  id: token_prefix
  attributes:
    label: Token Prefix 
    placeholder: "nrelop"
    description:
- type: dropdown
  id: map_heatmap
  attributes:
    label: Map Heatmap 
    description: 
    default: 0
    options:  
      - "true"
      - "false"
  validations:
    required: true
- type: dropdown
  id: map_bubble
  attributes:
    label: Map Bubble 
    description: 
    default: 0
    options:  
      - "true"
      - "false"
  validations:
    required: true
- type: dropdown
  id: map_trip_lines
  attributes:
    label: Map Trip Lines
    description: 
    default: 1
    options:  
      - "true"
      - "false"
  validations:
    required: true
- type: dropdown
  id: push_send
  attributes:
    label: Push Send
    description: 
    default: 1
    options:  
      - "true"
      - "false"
  validations:
    required: true
- type: dropdown
  id: options_uuids
  attributes:
    label: Options UUIDs
    description: 
    default: 0
    options:  
      - "true"
      - "false"
  validations:
    required: true
- type: dropdown
  id: options_emails
  attributes:
    label: Options Emails
    description: 
    default: 0
    options:  
      - "true"
      - "false"
  validations:
    required: true
