name: Convert Issues to JSON Data

on:
  issues:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issues
    types:
      - opened
      - edited
      - reopened
      - labeled

jobs:
  convert_to_config:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - name: Check out repository
        uses: actions/checkout@v4
      - name: install dependencies
        shell: bash -l {0}
        run: | 
          npm install js-yaml
          npm i @actions/core
          npm i @actions/github
      # This step references the directory that contains the action.
      - name: Use local convertIssue action
        uses: ./.github/actions/convertIssue
